# Swipe Down with 3 Fingers -> Open Control Center
gesture swipe down 3 ~/.config/rofi/cyber_card.sh
# Optional: Swipe Up with 3 Fingers -> Close Rofi (pkill)
gesture swipe up 3 pkill rofi

# Swipe Left -> Next Workspace (Using Full Path)
gesture swipe left 3 /usr/bin/hyprctl dispatch workspace -1

# Swipe Right -> Previous Workspace (Using Full Path)
gesture swipe right 3 /usr/bin/hyprctl dispatch workspace +1

# Swipe Down 4: Go to "special" empty workspace (Simulates Minimize All)
gesture swipe down 4 hyprctl dispatch movetoworkspacesilent special
# Swipe Up 4: Return from special workspace (Simulates Pop Up/Restore)
gesture swipe up 4 hyprctl dispatch togglespecialworkspace
